[project]
name = "stmhybridmodel"
version = "0.1.0"
description = "A hybrid model describing the biological dynamics of STM in pluripotent/differentiated cells."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "numba>=0.65.1",
    "numba-progress>=1.2.0",
    "numpy>=2.4.6",
    "seaborn>=0.13.2",
    "sympy>=1.14.0",
]

[tool.uv]
cache-dir = ".uv_cache"
